= 自驱者的原动力是什么？

在知乎上看到有家长问：小学需要培养孩子的哪些学习习惯?

看了评论区，很多答主和宝妈的回答，例如，培养孩子学习，阅读，朗读，思考，预习，复习，专心听讲，积极发言，求知欲，积极性…… 等等习惯。

我认为这更多是父母在许愿，如果许愿可行，那直接拜佛求神不是更好吗？

方法是督促，监督，错题本，预习，补课…… 有用吗？

我认为都是浅层知识。

让我教你更高维度的知识




习惯是培养出来的？习惯是逼出来的吗？
人类是如何驯化动物的

为什么狗狗乖，会听话，你是怎么训练它的？
透过投喂建立条件反射
不听话就打
打完再安抚
怎样培养孩子的习惯

建立孩子的习惯其实很简单，要从人性的角度出发

加油者

你看看其他答主都给出什么建议，多数人告诉你，读书，运动。你点开这些答主的头像看看，他们都是什么人？他们自己都做不到的事情，让别人去做。
人们都擅长做加油鼓励者，而不是亲自下场参战。是不是跟各位家长一样，几乎所有家长都鼓励孩子，鸡娃，而不是对自己狠点，鸡自己。笨鸟先飞，笨鸟自己不打算飞，而是在窝里生蛋，他们把希望寄托在蛋上。
自驱者的原动力

人要想横下心来做一件事的动机是什么？是理想吗？是目标吗？是信念吗？
都不是，所谓理想、目标、信念都是溢美之词，说的太高大上了，其实没有那么高尚，人是激素驱动的动物，人的一切行为是激素作用的结果。
各位想想你们的初恋，当你第一次拥抱孩女是情景，不由自主地生理勃起，女孩被吻过之后是不是瞬间上头，近乎昏迷，甚至发出呻吟。这就是激素作用，你用精神和意志力也难以控制，同时会建立激励回路，让你下次还想要。
知道这个原理之后，我们做的就简单了，你做任何事情要考虑，是否能达到激励回路，让身体分批多巴胺，内啡肽奖励你。以健身和体育运动为例。
为什么健身很难坚持？
健身产生多巴胺，建立大脑奖赏回路，本质上是一种激素驱动行为。你之所以爱健身，迷上了健身，是在你运动时，身体激素在持续奖励你，所以我说健身是一种自慰行为。
很多人认为健身的人具备自律，自驱，自我管理…… 等等优秀的品质，的确成功人士都很自律，但是为啥更多自律的人都不成功？？？
仔细想想「自律」这个词，为啥会有那么多人去「健身」？而不是去「读书」？
精神激励方法

获得精神上的激励回路的难度，远远大于肉体。肉体是直接通过神经网络触发人体激素分泌，仅需零点几秒就能达到效果。例如去爱抚女性的身体，甭说是私密部位，就是女孩的手跟脚，都能瞬间让你上头。你的大脑会瞬间分泌激素（激素的英文是荷尔蒙HORMONES）奖励你。
对比去看名著《金瓶梅》效果明显差很多，我是多次拿起，放下，至今都无法读完这部伟大的作品。估计除非是单身，没有体验过肌肤之亲的人可以读完。
因为精神上的自律，远比肉体上的自律更难。你能做到肉体上禁欲，却难阻止精神上意淫。
怎样建立精神激励回路

只有毒品能够阻断激素，并立即建立更强的激励回路，几乎没有人能通过意志力戒掉毒品，毒品更直接，例如海洛因只需吸三次就能建立回路。
这就是西方最初研发毒品的原动力，他们起初是给艺术家使用的，艺术家通过吸入毒品，可以获得更多的创作灵感，毒品能激发他们的想象力。但是毒品的副作用太大，副作用蚕食自身健康。最终人们放弃了，通过毒品来建立激励回路的想法。
建立精神激励回路的时间也远远比肉体更长，需要长期坚持和训练，这也是有技巧的。
我就一读书学习为例吧，之所以人们无法坚持读书学习，是因为没能建立激励回路，行程奖励闭环。成人读书跟孩子上学一样，不同的是孩子还有外部驱动，即家长和老师的鞭策和监督。而成人就只能依赖自己的意志力，你嗷嗷的学，学了之后呢？就没有之后了，所以没有建立激励回路。
你应该这样学习
读书 -> 总结 -> 输出 -> 分享 -> 收到（点赞、收藏、分享）-> 粉丝回馈 -> 再创作
当你粉丝量达到一定规模之后，还能带货赚钱，你就会更有动力。
但是这个非常难的，你会发现知乎上大量的用户，是做不到的，他们更喜欢做「加油者」